@baseurl = http://localhost:3003

### GET all blogs
GET {{baseurl}}/api/blogs
# Expected: 200 OK
# Body: An array of blog objects (empty [] if first time)

### [SUCCESS] Post a valid new blog
POST {{baseurl}}/api/blogs
Content-Type: application/json

{
  "title": "Systems Engineering in Node",
  "author": "Cristian Mamani",
  "url": "https://fullstackopen.com/",
  "likes": 5
}
### Expected: 201 Created
### Body: The saved blog object including _id and __v



### -----------------------USERS
### GET all users
GET {{baseurl}}/api/users
# Expected: 200 OK
# Body: An array of users objects (empty [] if first time)


### [SUCCESS] Post a valid new user
POST {{baseurl}}/api/users/
Content-Type: application/json

{
    "username": "root",
    "name": "Superuser",
    "password": "salainen"
}
### Expected: 201 Created
### Body: The saved blog object including _id and __v



### -----------------------BLOGS

### [SUCCESS] Post a valid new blog
POST {{baseurl}}/api/blogs/
Content-Type: application/json

{
    "title": "User id of the blog creator is at the start sent along the request",
    "author": "Cristian Mamani Aguirre",
    "url": "https://fullstackopen.com/",
    "likes": "0",
    "userId": "69c3278153f22852f28b7859"
}
### Expected: 201 Created

###-----------------LOGIN

### create user
POST {{baseurl}}/api/users/
Content-Type: application/json

{
    "username": "mluukkai",
    "name": "helsinki user",
    "password": "salainen"
}


### try to Login
POST {{baseurl}}/api/login/
Content-Type: application/json

{
    "username": "mluukkai",
    "password": "salainen"
}




### ------try with token
POST {{baseurl}}/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im1sdXVra2FpIiwiaWQiOiI2OWM0MDY4N2RhNjE2OWY3MzZiZWUyZmEiLCJpYXQiOjE3NzQ0NTQ4Mjh9.iPqUgsDWElEWvkIIw4s6IfDeRf-BScXn-WU6196ZvVE

{
    "title": "Canonical string reduction 2",
    "author": "Edsger 2",
    "url": "http://2www.cs.utexas.edu/~EWD/transcriptions/EWD08xx/EWD808.html",
    "likes": 2
  }

