### Get root endpoint
GET http://localhost:3001/

### Get all persons
GET http://localhost:3001/api/persons

### Get info page
GET http://localhost:3001/info

### Get person with ID 1
GET http://localhost:3001/api/persons/1

### Get person with ID 10 (likely non-existent)
GET http://localhost:3001/api/persons/10

### Delete person with ID 1
DELETE http://localhost:3001/api/persons/1
